/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        CppToGraph classUnderTest = new CppToGraph();
       // assertEquals("引数には解析ディレクトリ(ファイル)+出力ディレクトリを指定してください", classUnderTest.main(null));
    }
}
